dist: trusty

language: go

services:
  - docker

addons:
  apt:
    packages:
    - libxml2-dev
    - libcunit1-dev

go:
  - 1.8
  - 1.9

go_import_path: gopkg.in/src-d/hercules.v3

before_install:
  - wget http://mirrors.kernel.org/ubuntu/pool/main/m/make-dfsg/make_4.1-9.1_amd64.deb
  - dpkg -x make_4.1-9.1_amd64.deb ~ && rm make_4.1-9.1_amd64.deb
  - wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py --user && rm get-pip.py
  - export PATH=~/.local/bin:~/usr/bin:$PATH
  - make --version
  - pip3 --version

install:
  - make dependencies
  - go get -t -v -ldflags "-X gopkg.in/src-d/hercules.v3.GIT_HASH=$(git rev-parse HEAD)" ./...
  - pip3 install --user -r requirements.txt tensorflow
  - docker run -d --privileged -p 9432:9432 --name bblfshd bblfsh/bblfshd
  - docker exec -it bblfshd bblfshctl driver install --all
  
script:
  - go vet .
  - go test -v -cpu=1,2 -coverprofile=coverage.txt -covermode=count gopkg.in/src-d/hercules.v3
  - $GOPATH/bin/hercules -version
  - $GOPATH/bin/hercules -burndown -burndown-files -burndown-people -couples -quiet https://github.com/src-d/hercules | python3 labours.py -m all -o out --backend Agg --disable-projector
  - $GOPATH/bin/hercules -burndown -burndown-files -burndown-people -couples -quiet -pb https://github.com/src-d/hercules | python3 labours.py -f pb -m all -o out --backend Agg --disable-projector
  - $GOPATH/bin/hercules-generate-plugin -version
  - $GOPATH/bin/hercules-generate-plugin -n MyTest && test -e my_test.go

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
