[[override]]
  name = "github.com/xanzy/ssh-agent"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/Masterminds/sprig"

[[constraint]]
  branch = "master"
  name = "github.com/fatih/camelcase"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/jeffail/tunny"

[[constraint]]
  branch = "master"
  name = "github.com/minio/highwayhash"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  revision = "da645544ed44df016359bd4c0e3dc60ee3a0da43"
  name = "github.com/sergi/go-diff"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.2"

[[constraint]]
  revision = "5b93e2dc01fd8fbf32aa74a198b0ebe78f6f6b6f"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/bblfsh/client-go.v2"
  version = "2.8.8"

[[constraint]]
  name = "gopkg.in/bblfsh/sdk.v1"
  version = "1.16.1"

[[constraint]]
  branch = "master"
  name = "gopkg.in/cheggaaa/pb.v1"

[[constraint]]
  branch = "master"
  name = "gopkg.in/src-d/enry.v1"

[[constraint]]
  branch = "master"
  name = "gopkg.in/src-d/go-billy-siva.v4"

[[constraint]]
  branch = "master"
  name = "gopkg.in/src-d/go-billy.v4"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.7.1"

[[constraint]]
  branch = "master"
  name = "gopkg.in/vmarkovtsev/BiDiSentiment.v1"

[prune]
  go-tests = true
  unused-packages = true
