language: dockerfile
extensions:
- Dockerfile
- .dockerfile
parser: tree-sitter
mapping:
  comment:
    type: Comment
    roles:
    - Comment
  variable:
    type: Variable
    roles:
    - Variable
  from_instruction:
    type: FromInstruction
    roles:
    - Declaration
    props:
      image: Image
      tag: Tag
  copy_instruction:
    type: CopyInstruction
    roles:
    - Declaration
    props:
      source: Source
      destination: Destination
  add_instruction:
    type: AddInstruction
    roles:
    - Declaration
    props:
      source: Source
      destination: Destination
  run_instruction:
    type: RunInstruction
    roles:
    - Declaration
    props:
      command: Command
  cmd_instruction:
    type: CmdInstruction
    roles:
    - Declaration
    props:
      command: Command
  entrypoint_instruction:
    type: EntrypointInstruction
    roles:
    - Declaration
    props:
      command: Command
  env_instruction:
    type: EnvInstruction
    roles:
    - Declaration
  expose_instruction:
    type: ExposeInstruction
    roles:
    - Declaration
    props:
      port: Port
  volume_instruction:
    type: VolumeInstruction
    roles:
    - Declaration
  user_instruction:
    type: UserInstruction
    roles:
    - Declaration
    props:
      user: User
  workdir_instruction:
    type: WorkdirInstruction
    roles:
    - Declaration
    props:
      path: Path
  arg_instruction:
    type: ArgInstruction
    roles:
    - Declaration
    props:
      name: Name
  onbuild_instruction:
    type: OnbuildInstruction
    roles:
    - Declaration
  label_instruction:
    type: LabelInstruction
    roles:
    - Declaration
  shell_instruction:
    type: ShellInstruction
    roles:
    - Declaration
    props:
      shell: Shell
  stopsignal_instruction:
    type: StopsignalInstruction
    roles:
    - Declaration
    props:
      signal: Signal
  healthcheck_instruction:
    type: HealthcheckInstruction
    roles:
    - Declaration
  maintainer_instruction:
    type: MaintainerInstruction
    roles:
    - Declaration
    props:
      maintainer: Maintainer
