// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: hercules.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_hercules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{0}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Config        map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_hercules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HealthResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *HealthResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// List analyses request
type ListAnalysesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalysesRequest) Reset() {
	*x = ListAnalysesRequest{}
	mi := &file_hercules_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalysesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalysesRequest) ProtoMessage() {}

func (x *ListAnalysesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalysesRequest.ProtoReflect.Descriptor instead.
func (*ListAnalysesRequest) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{2}
}

// Analysis type information
type AnalysisType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisType) Reset() {
	*x = AnalysisType{}
	mi := &file_hercules_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisType) ProtoMessage() {}

func (x *AnalysisType) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisType.ProtoReflect.Descriptor instead.
func (*AnalysisType) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{3}
}

func (x *AnalysisType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnalysisType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnalysisType) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// List analyses response
type ListAnalysesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analyses      []*AnalysisType        `protobuf:"bytes,1,rep,name=analyses,proto3" json:"analyses,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalysesResponse) Reset() {
	*x = ListAnalysesResponse{}
	mi := &file_hercules_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalysesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalysesResponse) ProtoMessage() {}

func (x *ListAnalysesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalysesResponse.ProtoReflect.Descriptor instead.
func (*ListAnalysesResponse) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{4}
}

func (x *ListAnalysesResponse) GetAnalyses() []*AnalysisType {
	if x != nil {
		return x.Analyses
	}
	return nil
}

func (x *ListAnalysesResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Submit analysis request
type SubmitAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Analyses      []string               `protobuf:"bytes,2,rep,name=analyses,proto3" json:"analyses,omitempty"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnalysisRequest) Reset() {
	*x = SubmitAnalysisRequest{}
	mi := &file_hercules_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnalysisRequest) ProtoMessage() {}

func (x *SubmitAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnalysisRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitAnalysisRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SubmitAnalysisRequest) GetAnalyses() []string {
	if x != nil {
		return x.Analyses
	}
	return nil
}

func (x *SubmitAnalysisRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// Submit analysis response
type SubmitAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnalysisResponse) Reset() {
	*x = SubmitAnalysisResponse{}
	mi := &file_hercules_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnalysisResponse) ProtoMessage() {}

func (x *SubmitAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnalysisResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitAnalysisResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitAnalysisResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitAnalysisResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitAnalysisResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Get analysis status request
type GetAnalysisStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisStatusRequest) Reset() {
	*x = GetAnalysisStatusRequest{}
	mi := &file_hercules_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisStatusRequest) ProtoMessage() {}

func (x *GetAnalysisStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisStatusRequest) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnalysisStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Analysis result
type AnalysisResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ResultType    string                 `protobuf:"bytes,3,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_hercules_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{8}
}

func (x *AnalysisResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnalysisResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnalysisResult) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *AnalysisResult) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// Get analysis status response
type GetAnalysisStatusResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        string                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JobId         string                     `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StartTime     *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Results       map[string]*AnalysisResult `protobuf:"bytes,6,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp     `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisStatusResponse) Reset() {
	*x = GetAnalysisStatusResponse{}
	mi := &file_hercules_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisStatusResponse) ProtoMessage() {}

func (x *GetAnalysisStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAnalysisStatusResponse) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{9}
}

func (x *GetAnalysisStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAnalysisStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAnalysisStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetAnalysisStatusResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetAnalysisStatusResponse) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetAnalysisStatusResponse) GetResults() map[string]*AnalysisResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetAnalysisStatusResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Stream analysis progress request
type StreamAnalysisProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAnalysisProgressRequest) Reset() {
	*x = StreamAnalysisProgressRequest{}
	mi := &file_hercules_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAnalysisProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAnalysisProgressRequest) ProtoMessage() {}

func (x *StreamAnalysisProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAnalysisProgressRequest.ProtoReflect.Descriptor instead.
func (*StreamAnalysisProgressRequest) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{10}
}

func (x *StreamAnalysisProgressRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Stream analysis progress response
type StreamAnalysisProgressResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamAnalysisProgressResponse) Reset() {
	*x = StreamAnalysisProgressResponse{}
	mi := &file_hercules_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAnalysisProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAnalysisProgressResponse) ProtoMessage() {}

func (x *StreamAnalysisProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hercules_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAnalysisProgressResponse.ProtoReflect.Descriptor instead.
func (*StreamAnalysisProgressResponse) Descriptor() ([]byte, []int) {
	return file_hercules_proto_rawDescGZIP(), []int{11}
}

func (x *StreamAnalysisProgressResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StreamAnalysisProgressResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StreamAnalysisProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamAnalysisProgressResponse) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *StreamAnalysisProgressResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_hercules_proto protoreflect.FileDescriptor

const file_hercules_proto_rawDesc = "" +
	"\n" +
	"\x0ehercules.proto\x12\vhercules.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\x0f\n" +
	"\rHealthRequest\"\x8c\x02\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12?\n" +
	"\x06config\x18\x05 \x03(\v2'.hercules.v1.HealthResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13ListAnalysesRequest\"^\n" +
	"\fAnalysisType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\"\x87\x01\n" +
	"\x14ListAnalysesResponse\x125\n" +
	"\banalyses\x18\x01 \x03(\v2\x19.hercules.v1.AnalysisTypeR\banalyses\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xda\x01\n" +
	"\x15SubmitAnalysisRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x1a\n" +
	"\banalyses\x18\x02 \x03(\tR\banalyses\x12I\n" +
	"\aoptions\x18\x03 \x03(\v2/.hercules.v1.SubmitAnalysisRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x16SubmitAnalysisResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"1\n" +
	"\x18GetAnalysisStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x91\x01\n" +
	"\x0eAnalysisResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vresult_type\x18\x03 \x01(\tR\n" +
	"resultType\x12(\n" +
	"\x04data\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x04data\"\xb8\x03\n" +
	"\x19GetAnalysisStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12M\n" +
	"\aresults\x18\x06 \x03(\v23.hercules.v1.GetAnalysisStatusResponse.ResultsEntryR\aresults\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1aW\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.hercules.v1.AnalysisResultR\x05value:\x028\x01\"6\n" +
	"\x1dStreamAnalysisProgressRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xce\x01\n" +
	"\x1eStreamAnalysisProgressResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x05R\x0fprogressPercent\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xdd\x03\n" +
	"\x0fHerculesService\x12A\n" +
	"\x06Health\x12\x1a.hercules.v1.HealthRequest\x1a\x1b.hercules.v1.HealthResponse\x12S\n" +
	"\fListAnalyses\x12 .hercules.v1.ListAnalysesRequest\x1a!.hercules.v1.ListAnalysesResponse\x12Y\n" +
	"\x0eSubmitAnalysis\x12\".hercules.v1.SubmitAnalysisRequest\x1a#.hercules.v1.SubmitAnalysisResponse\x12b\n" +
	"\x11GetAnalysisStatus\x12%.hercules.v1.GetAnalysisStatusRequest\x1a&.hercules.v1.GetAnalysisStatusResponse\x12s\n" +
	"\x16StreamAnalysisProgress\x12*.hercules.v1.StreamAnalysisProgressRequest\x1a+.hercules.v1.StreamAnalysisProgressResponse0\x01B4Z2github.com/dmytrogajewski/hercules/api/proto/pb;pbb\x06proto3"

var (
	file_hercules_proto_rawDescOnce sync.Once
	file_hercules_proto_rawDescData []byte
)

func file_hercules_proto_rawDescGZIP() []byte {
	file_hercules_proto_rawDescOnce.Do(func() {
		file_hercules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hercules_proto_rawDesc), len(file_hercules_proto_rawDesc)))
	})
	return file_hercules_proto_rawDescData
}

var file_hercules_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_hercules_proto_goTypes = []any{
	(*HealthRequest)(nil),                  // 0: hercules.v1.HealthRequest
	(*HealthResponse)(nil),                 // 1: hercules.v1.HealthResponse
	(*ListAnalysesRequest)(nil),            // 2: hercules.v1.ListAnalysesRequest
	(*AnalysisType)(nil),                   // 3: hercules.v1.AnalysisType
	(*ListAnalysesResponse)(nil),           // 4: hercules.v1.ListAnalysesResponse
	(*SubmitAnalysisRequest)(nil),          // 5: hercules.v1.SubmitAnalysisRequest
	(*SubmitAnalysisResponse)(nil),         // 6: hercules.v1.SubmitAnalysisResponse
	(*GetAnalysisStatusRequest)(nil),       // 7: hercules.v1.GetAnalysisStatusRequest
	(*AnalysisResult)(nil),                 // 8: hercules.v1.AnalysisResult
	(*GetAnalysisStatusResponse)(nil),      // 9: hercules.v1.GetAnalysisStatusResponse
	(*StreamAnalysisProgressRequest)(nil),  // 10: hercules.v1.StreamAnalysisProgressRequest
	(*StreamAnalysisProgressResponse)(nil), // 11: hercules.v1.StreamAnalysisProgressResponse
	nil,                                    // 12: hercules.v1.HealthResponse.ConfigEntry
	nil,                                    // 13: hercules.v1.SubmitAnalysisRequest.OptionsEntry
	nil,                                    // 14: hercules.v1.GetAnalysisStatusResponse.ResultsEntry
	(*timestamppb.Timestamp)(nil),          // 15: google.protobuf.Timestamp
	(*anypb.Any)(nil),                      // 16: google.protobuf.Any
}
var file_hercules_proto_depIdxs = []int32{
	15, // 0: hercules.v1.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	12, // 1: hercules.v1.HealthResponse.config:type_name -> hercules.v1.HealthResponse.ConfigEntry
	3,  // 2: hercules.v1.ListAnalysesResponse.analyses:type_name -> hercules.v1.AnalysisType
	15, // 3: hercules.v1.ListAnalysesResponse.timestamp:type_name -> google.protobuf.Timestamp
	13, // 4: hercules.v1.SubmitAnalysisRequest.options:type_name -> hercules.v1.SubmitAnalysisRequest.OptionsEntry
	15, // 5: hercules.v1.SubmitAnalysisResponse.timestamp:type_name -> google.protobuf.Timestamp
	16, // 6: hercules.v1.AnalysisResult.data:type_name -> google.protobuf.Any
	15, // 7: hercules.v1.GetAnalysisStatusResponse.start_time:type_name -> google.protobuf.Timestamp
	15, // 8: hercules.v1.GetAnalysisStatusResponse.end_time:type_name -> google.protobuf.Timestamp
	14, // 9: hercules.v1.GetAnalysisStatusResponse.results:type_name -> hercules.v1.GetAnalysisStatusResponse.ResultsEntry
	15, // 10: hercules.v1.GetAnalysisStatusResponse.timestamp:type_name -> google.protobuf.Timestamp
	15, // 11: hercules.v1.StreamAnalysisProgressResponse.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 12: hercules.v1.GetAnalysisStatusResponse.ResultsEntry.value:type_name -> hercules.v1.AnalysisResult
	0,  // 13: hercules.v1.HerculesService.Health:input_type -> hercules.v1.HealthRequest
	2,  // 14: hercules.v1.HerculesService.ListAnalyses:input_type -> hercules.v1.ListAnalysesRequest
	5,  // 15: hercules.v1.HerculesService.SubmitAnalysis:input_type -> hercules.v1.SubmitAnalysisRequest
	7,  // 16: hercules.v1.HerculesService.GetAnalysisStatus:input_type -> hercules.v1.GetAnalysisStatusRequest
	10, // 17: hercules.v1.HerculesService.StreamAnalysisProgress:input_type -> hercules.v1.StreamAnalysisProgressRequest
	1,  // 18: hercules.v1.HerculesService.Health:output_type -> hercules.v1.HealthResponse
	4,  // 19: hercules.v1.HerculesService.ListAnalyses:output_type -> hercules.v1.ListAnalysesResponse
	6,  // 20: hercules.v1.HerculesService.SubmitAnalysis:output_type -> hercules.v1.SubmitAnalysisResponse
	9,  // 21: hercules.v1.HerculesService.GetAnalysisStatus:output_type -> hercules.v1.GetAnalysisStatusResponse
	11, // 22: hercules.v1.HerculesService.StreamAnalysisProgress:output_type -> hercules.v1.StreamAnalysisProgressResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_hercules_proto_init() }
func file_hercules_proto_init() {
	if File_hercules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hercules_proto_rawDesc), len(file_hercules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hercules_proto_goTypes,
		DependencyIndexes: file_hercules_proto_depIdxs,
		MessageInfos:      file_hercules_proto_msgTypes,
	}.Build()
	File_hercules_proto = out.File
	file_hercules_proto_goTypes = nil
	file_hercules_proto_depIdxs = nil
}
