# Default values for hercules
replicaCount: 3

image:
  repository: ghcr.io/dmytrogajewski/hercules
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  grpcPort: 9090

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: hercules.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Hercules configuration
config:
  server:
    port: 8080
    host: "0.0.0.0"
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"
  
  grpc:
    enabled: true
    port: 9090
    host: "0.0.0.0"
  
  cache:
    enabled: true
    backend: "s3"
    s3_bucket: "hercules-cache"
    s3_region: "us-east-1"
    s3_prefix: "hercules"
    ttl: "168h"
  
  analysis:
    default_tick_size: 24
    default_granularity: 30
    default_sampling: 30
    max_concurrent_analyses: 5
    timeout: "30m"
  
  logging:
    level: "info"
    format: "json"
    output: "stdout"
  
  repository:
    clone_timeout: "10m"
    max_file_size: "1MB"
    allowed_protocols: ["https", "http", "ssh", "git"]

# AWS S3 credentials (optional - can use IAM roles)
aws:
  accessKeyId: ""
  secretAccessKey: ""
  region: "us-east-1"

# Environment variables
env: {}
  # HERCULES_CACHE_S3_BUCKET: "hercules-cache"
  # HERCULES_CACHE_S3_REGION: "us-east-1"
  # HERCULES_CACHE_S3_PREFIX: "hercules"
  # HERCULES_CACHE_TTL: "168h" 